// GET /api/queries/export?id=<query_id>&format=json|txt
import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabase } from '@/lib/supabase/server'

export async function GET(request: NextRequest) {
  const supabase = createServerSupabase()
  const { data: { user }, error } = await supabase.auth.getUser()
  if (error || !user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(request.url)
  const queryId = searchParams.get('id')
  const format = searchParams.get('format') || 'json'

  if (!queryId) return NextResponse.json({ error: 'Query ID required' }, { status: 400 })

  const { data: query, error: qErr } = await supabase
    .from('research_queries')
    .select('*, documents(title, original_filename)')
    .eq('id', queryId)
    .eq('user_id', user.id)
    .single()

  if (qErr || !query) return NextResponse.json({ error: 'Query not found' }, { status: 404 })
  if (!query.result) return NextResponse.json({ error: 'No result to export' }, { status: 400 })

  const result = query.result
  const docTitle = (query.documents as any)?.title || 'Unknown Document'

  if (format === 'txt') {
    const lines = [
      `RESEARCH REPORT`,
      `${'='.repeat(60)}`,
      `Document: ${docTitle}`,
      `Query: ${query.query}`,
      `Generated: ${new Date(query.created_at).toLocaleString('en-IN')}`,
      `Model: ${query.model_used || 'N/A'}`,
      `Confidence: ${Math.round(result.confidence_score * 100)}%`,
      ``,
      `TOPIC`,
      `${'-'.repeat(40)}`,
      result.topic,
      ``,
      `SUMMARY`,
      `${'-'.repeat(40)}`,
      result.summary,
      ``,
      `KEY POINTS`,
      `${'-'.repeat(40)}`,
      ...result.key_points.map((p: string, i: number) => `${i + 1}. ${p}`),
      ``,
      `INSIGHTS`,
      `${'-'.repeat(40)}`,
      ...result.insights.map((ins: string, i: number) => `• ${ins}`),
    ]

    if (result.citations?.length > 0) {
      lines.push(``, `CITATIONS`, `${'-'.repeat(40)}`)
      result.citations.forEach((c: any, i: number) => {
        lines.push(`[${i + 1}] ${c.source}`)
        lines.push(`    "${c.text}"`)
      })
    }

    if (result.limitations) {
      lines.push(``, `LIMITATIONS`, `${'-'.repeat(40)}`, result.limitations)
    }

    lines.push(``, `${'='.repeat(60)}`, `Generated by ResearchAI — https://researchai.app`)

    const text = lines.join('\n')
    return new NextResponse(text, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="research-report-${queryId.slice(0, 8)}.txt"`,
      },
    })
  }

  // JSON export
  const exportData = {
    meta: {
      exported_at: new Date().toISOString(),
      query_id: queryId,
      document: docTitle,
      model_used: query.model_used,
      processing_time_ms: query.processing_time_ms,
    },
    query: query.query,
    result,
  }

  return new NextResponse(JSON.stringify(exportData, null, 2), {
    headers: {
      'Content-Type': 'application/json',
      'Content-Disposition': `attachment; filename="research-report-${queryId.slice(0, 8)}.json"`,
    },
  })
}
